# apiVersion: kargo.akuity.io/v1alpha1
# kind: Project
# metadata:
#   name: kargo-resources  # this manifest use to create namespace for project resources


                    kargo-demo
                     Project
                        │
            ┌───────────┴───────────┐
            │                       │
      ProjectConfig             Warehouse
            │                       │
      pipeline rules               ECR
                                    │
                              new image v1.2.0
                                    │
                                    ↓
                                  Freight
                                    │
                                    ↓
                                  dev
                                    │
                          automatic promotion
                                    ↓
                                 stage
                                    │
                          automatic promotion
                                    ↓
                                  prod
                                    │
                           manual promotion