apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-resources
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: dev
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "${{ vars.env }}: bump myapp to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./src
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: kargo-resources
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        stages: [dev]
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: stage
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "${{ vars.env }}: bump myapp to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./src
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-resources
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        stages: [stage]
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: prod
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "${{ vars.env }}: bump myapp to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./src
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}