apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev       # it describes things such as which Freight it can use, how promotion happens, how verification works
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: dev
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
              - branch: ${{ vars.env }}
                path: ./out
        - uses: git-clear
          config:
            path: ./out
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: kustomize-build
          config:
            path: ./src/overlays/${{ vars.env }}
            outPath: ./out
        - uses: git-commit
          as: commit
          config:
            path: ./out
            message: "${{ vars.env }}: bump kargo-app to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./out
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
  verification:
    analysisTemplates:
      - name: smoke-test
    args:
      - name: env
        value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        stages: [dev]
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: stage
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
              - branch: ${{ vars.env }}
                path: ./out
        - uses: git-clear
          config:
            path: ./out
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: kustomize-build
          config:
            path: ./src/overlays/${{ vars.env }}
            outPath: ./out
        - uses: git-commit
          as: commit
          config:
            path: ./out
            message: "${{ vars.env }}: bump kargo-app to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./out
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
  verification:
    analysisTemplates:
      - name: smoke-test
    args:
      - name: env
        value: stage
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: kargo }
      sources:
        stages: [stage]
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/Mahmoud123759/kargo-demo-app.git
        - name: imageRepo
          value: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        - name: env
          value: prod
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src
              - branch: ${{ vars.env }}
                path: ./out
        - uses: git-clear
          config:
            path: ./out
        - uses: kustomize-set-image
          config:
            path: ./src/overlays/${{ vars.env }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: kustomize-build
          config:
            path: ./src/overlays/${{ vars.env }}
            outPath: ./out
        - uses: git-commit
          as: commit
          config:
            path: ./out
            message: "${{ vars.env }}: bump kargo-app to ${{ imageFrom(vars.imageRepo).Tag }}"
        - uses: git-push
          config:
            path: ./out
        - uses: argocd-update
          config:
            apps:
              - name: gitops-app-${{ vars.env }}
                namespace: argocd
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
  verification:
    analysisTemplates:
      - name: smoke-test
    args:
      - name: env
        value: prod