apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interval: 2m
  subscriptions:
    - image:
        repoURL: 345259854056.dkr.ecr.us-east-1.amazonaws.com/kargo-app
        imageSelectionStrategy: SemVer      # or NewestBuild
        constraint: ^1.0.0
        discoveryLimit: 10